"use client";
import "antd/dist/antd.css";
import { store } from "@/store";
import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import { Provider } from "react-redux";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Layout } from "antd";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Crypto currency</title>
        <meta name="description" content="" />
      </head>
      <body className={inter.className}>
        <Provider store={store}>
          <main className="app">
            <Navbar />
            <div className="main">
              <Layout>{children}</Layout>
              <Footer />
            </div>
          </main>
        </Provider>
      </body>
    </html>
  );
}
